# Use postgres/example user/password credentials
# When using 'docker-compose up' it's possible that the Flyway container starts before the database is up, causing an error
# In this case just do a relaunch.
# TODO: integrate wait-for-it.sh or something to wait until DB is up before running Flyway

version: '3.1'

services:
  db:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  flyway:
    build:
      context: ./db
    command: -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=example migrate
    depends_on:
      - db
