# Use postgres/example user/password credentials
# When using 'docker-compose up' it's possible that the Flyway container starts before the database is up, causing an error
# In this case just do a relaunch.
# TODO: integrate wait-for-it.sh or something to wait until DB is up before running Flyway

version: '3.1'

services:
  db:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    ports:
      - 5432:5432

  service:
    env_file:
      - .env
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      APP_VERSION: Compose
    build:
      context: .
    command: runShadow
    ports:
      - 4567:4567
