# Build
# This is the latest gradle Docker image available on the client with JDK8 support
FROM gradle:4.8.1-jdk8
USER root

# Make client repos available inside this image if necessary
# And disable Gradle daemon
ENV GRADLE_USER_HOME /opt
COPY docker/gradle-config/ $GRADLE_USER_HOME/

# Copy project sources
COPY build.gradle.kts settings.gradle.kts ./

# Copy Database Migration scripts and sources
COPY db ./db

ENTRYPOINT ["gradle", "--no-daemon", "-s", "-i"]
CMD ["flywayMigrate"]
