# Build
FROM gradle:4.7.0-jdk8
USER root

# Make client repos available inside this image if necessary
# And disable Gradle daemon
ENV GRADLE_USER_HOME /opt
COPY docker/gradle-config/ $GRADLE_USER_HOME/

# Copy config file
COPY .env ./

# Copy parent project sources
COPY build.gradle.kts settings.gradle.kts ./
COPY src ./src

# Copy Data Access Layer project sources
COPY dal ./dal

ENTRYPOINT ["gradle", "--no-daemon"]
CMD ["--help"]
