# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  flyway:
    build:
      context: ./db
    command: -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=example migrate
    depends_on:
      - db
