/*
 * This file is generated by jOOQ.
*/
package com.home.jooq;


import com.home.jooq.tables.Data;
import com.home.jooq.tables.Role;
import com.home.jooq.tables.User;
import com.home.jooq.tables.UserRole;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1",
        "schema version:3"
    },
    date = "2018-07-20T18:48:07.188Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DATA_PKEY = Indexes0.DATA_PKEY;
    public static final Index ROLE_PKEY = Indexes0.ROLE_PKEY;
    public static final Index USER_PKEY = Indexes0.USER_PKEY;
    public static final Index USER_ROLE_PKEY = Indexes0.USER_ROLE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index DATA_PKEY = createIndex("data_pkey", Data.DATA, new OrderField[] { Data.DATA.ID }, true);
        public static Index ROLE_PKEY = createIndex("role_pkey", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index USER_PKEY = createIndex("user_pkey", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_ROLE_PKEY = createIndex("user_role_pkey", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ID }, true);
    }
}
