/*
 * This file is generated by jOOQ.
*/
package com.home.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1",
        "schema version:3"
    },
    date = "2018-07-20T18:48:07.188Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.seq_data_id</code>
     */
    public static final Sequence<Long> SEQ_DATA_ID = new SequenceImpl<Long>("seq_data_id", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
